# -*- coding: utf-8 -*-
"""garage.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hhj3-xSfW9UhbNMk56ijfC5iGj05iLy3
"""

import pandas as pd
df = pd.read_csv("newGarage.csv")

print(df)

df.isnull().sum()

#"Because the Median is 'Robust'—it ignores outliers.
# While the Mean gets dragged away by extreme values (like a single massive maintenance cost),
# the Median stays in the center and represents what is actually 'typical' for the data."

mean_value = df["maintenance_cost"].mean()
df['maintenance_cost']=df["maintenance_cost"].fillna(mean_value)

median_amount=df["Amount"].median()
df['Amount'] = df["Amount"].fillna(median_amount)
df['Amount']

df["Date"]  = pd.to_datetime(df['Date'],format = 'mixed')

print(df["Date"])

df.isnull().sum()

#GRAPH FOR MONTH VS AMOUNT PER MONTH
import matplotlib.pyplot as plt

#what if there is a null value for date?
#If there is a missing date in a row it continues the very next date we use ffill() a.k.a forward fill
df['Date'] = df['Date'].ffill()


# 1. Group by Date and sum the Amount (in case of multiple entries per day)
daily_data = df.groupby("Date")["Amount"].sum().reset_index()


#2. Sorting dates for correct line flow
daily_data = daily_data.sort_values("Date")

#3. CReate the plot
plt.plot(daily_data["Date"], daily_data["Amount"],color = 'black' ,marker = 'o',linestyle= '-')

plt.title("Month vs Amount")
plt.xlabel("Month")
plt.ylabel("Amount")

#Horizontal Bar Graph for visualising top 5 clints
client_revenue = df.groupby("CLIENT")["Amount"].sum().reset_index()
top_5_clients  = client_revenue.sort_values("Amount")

plt.barh(top_5_clients["CLIENT"],top_5_clients["Amount"], color = 'green')
plt.title("Top 5 clients")
plt.xlabel("Amount")
plt.ylabel("Client name")
plt.show()



